name: smart_pay
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.1.2
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_svg: ^2.0.9
  get_it: ^7.6.7
  pinput: ^4.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3

flutter:

  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/svgs/
  fonts:
    - family: SF-Pro
      fonts:
        - asset: lib/assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: lib/assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: lib/assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: lib/assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
